### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by StephenGibbsDev** [ReikonKarite/FakeReddit#1]
- [x] SubReddit Routing
- [x] Add Post To SubReddit
- [x] Display Upvote using SQL query
- [x] Added Support to register via username
- [ ] Add Subreddit only for admin role
- [x] Upvote / Downvote functionality in subreddit posts
- [x] Comments System for posts.
- [x] Restrict Adding Post to logged in user
- [x] Create View Model within viewmodel to display comment/username info and allow for insertion of new comment.
- [x] big when adding post after inserting datetime field. need to format data before datbase insert.
- [ ] Find Bootstrap template / overhaul design
- [x] Edit functionality for posts / comments
- [ ] Overhaul routing
- [x] Fix bug where post information doesn't show when editing a comment
- [x] Add wysiwyg editor to posts box
- [x] Add wysiwyg editor to comment box
- [x] show number of comments a post has on subreddit index page.
- [x] Comment Number is bugged on subreddit index page - fix it
- [x] Change color of arrows depending if the user has clicked on it or not.
